### PR TITLE
Implement server-side timeout setting via environment variable

### PR DESCRIPTION
**Pull request by hexsprite**

### CODE REVIEW

**Comment by hexsprite** [comment]
Just realized I forgot to create the PR! :)

**Comment by SimonSimCity** [comment]
Thanks for taking the time of creating this PR. I'd like to merge this soon as well.

Please check if you'd not also get it working on the client side. This PR claims to also allow setting the timeout for the client: https://github.com/practicalmeteor/meteor-mocha-core/pull/9

**Comment by hexsprite** [comment]
@SimonSimCity it's not an itch I have at the moment and I can't spare any time to get it working on client side. As it, this does solve the server-side issue, so perhaps we can merge this and also work towards getting it working on client side when someone has the time?

**Comment by SimonSimCity** [comment]
@hexsprite thanks for providing the PR here. I've found some time yesterday to finish this up and test it through. The changes I've added to yours are visible here: https://github.com/meteortesting/meteor-mocha-core/commit/d1cd5dfae0e1dbf32aa944574e08eb6a3ca4797d

The major changes I did was renaming the environment variable to `MOCHA_TIMEOUT` which will set this timeout for the server and the client - it mainly was a code-copy of https://github.com/practicalmeteor/meteor-mocha-core/pull/9.

**Comment by hexsprite** [comment]
@SimonSimCity oh nice, that was a handy way of using Meteor.settings to pass data from server to client.

**Pull request merged**
