### PR TITLE
Fixed issue when .only() is provided for the tests

### PR DESCRIPTION
**Pull request by theodorDiaconu**
Original issue: https://github.com/meteortesting/meteor-mocha/issues/75

I am not confident about my fix, but it seems to solve it. If you have a better solution let me know. Amazing job on this package!

### CODE REVIEW

**Comment by theodorDiaconu** [comment]
Any updates on this. I really want to avoid forking and creating yet another package. @jsep @SimonSimCity @aldeed

**Comment by SimonSimCity** [comment]
I'm trying to reproduce it ... will spend some time in the coming hours on this, but I first want to have a way of reproducing it ... The change here looks like something that just touches the symptoms, but doesn't fix the actual problem - my first impression.

**Comment by theodorDiaconu** [comment]
@SimonSimCity indeed it's not a reliable fix that's for sure. I tried to investigate it myself, for some reason, it doesn't have the right context.

I just thought about this, what if we bind the context like this:
```js
  mochaExports["__org_it"].only.bind(mochaExports["__org_it"])
  mochaExports.it.only = (name, func) => {
    mochaExports["__org_it"].only(name, wrapRunnable(func));
  };
```

^ Update: Doesn't work. it seems that the `func` is

**Comment by SimonSimCity** [comment]
Do you have a repository where I could reproduce this error? This would give me a good possibility to join you fixing this 😉

**Comment by theodorDiaconu** [comment]
ping @SimonSimCity. Sorry no respository just spin-it up:

```
meteor create --full myapp
```

And for the server tests make all `.it` with it.only(). And don't forget to upgrade mocha-core to 5.x

**Comment by SimonSimCity** [comment]
I was now finally able to reproduce this bug and I have to say it took me quite some debugging through the Mocha package until I found the mistake exactly where you expected it: https://github.com/meteortesting/meteor-mocha-core/commit/e8d0d088b191b34c7da9cd1beefd9a00636238e9

It was actually also quite more than what you found. It actually also crashed when calling `this.timeout()` in a test after marking it as `only` 🙈

Thanks for pointing this out! This bug only touched tests, marked as `it.only()` - synchronous and asynchronous. I've already released a new version which should fix it. Please test it and write back if it worked. I've closed this rather unintentionally by committing the changes 😅 - see the commit message ...

If you discover something else, please feel free to open a ticket or PR. Help is always welcome!

**Pull request closed without merging**
